### ISSUE TITLE
8.1.0 fails but 7.13.0 runs error free

### ISSUE THREAD

**Issue by jsiegenthaler** [Borewit/music-metadata#1471]
music-metadata is a dependency of node-sonos-http-api 

When updating the dependencies of node-sonos-http-api  the following is observed:

With music-metadata v7.13.0:  node-sonos-http-api starts and runs without error

With music-metadata v8.1.0:  node-sonos-http-api throws the following errors:

```pi@raspberrypi:~/node-sonos-http-api $ npm start

> sonos-http-api@1.6.9 start
> node server.js

/home/pi/node-sonos-http-api/lib/helpers/file-duration.js:1
const musicMeta = require('music-metadata');
                  ^

Error [ERR_REQUIRE_ESM]: require() of ES Module /home/pi/node-sonos-http-api/node_modules/music-metadata/lib/index.js from /home/pi/node-sonos-http-api/lib/helpers/file-duration.js not supported.
Instead change the require of index.js in /home/pi/node-sonos-http-api/lib/helpers/file-duration.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/home/pi/node-sonos-http-api/lib/helpers/file-duration.js:1:19)
    at Object.<anonymous> (/home/pi/node-sonos-http-api/lib/actions/clip.js:3:22)
    at /home/pi/node-sonos-http-api/lib/helpers/require-dir.js:18:8
    at Array.forEach (<anonymous>)
    at module.exports (/home/pi/node-sonos-http-api/lib/helpers/require-dir.js:17:6)
    at new HttpAPI (/home/pi/node-sonos-http-api/lib/sonos-http-api.js:45:3)
    at Object.<anonymous> (/home/pi/node-sonos-http-api/server.js:14:13) {
  code: 'ERR_REQUIRE_ESM'
}
```

**Comment by Borewit** [comment]
See the release notes [v8.0.0](https://github.com/Borewit/music-metadata/releases/tag/v8.0.0).

Problem also discussed in #1364, #1357, #1352 .....
