### ISSUE TITLE
gg audio-codec not recognized (id=HXR        5)

### ISSUE THREAD

**Issue by Cayllen** [Borewit/music-metadata#1977]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### music-metadata version

8.2

### JavaScript module eco system

None

### Current Behavior

`parseFile('output.ogg', { duration: true })`

Throws an 
```
ERROR ERROR Error: gg audio-codec not recognized (id=HXR        5)   OR (id=Hy4)
    at OggParser.parse (file:///Users/xxx/Desktop/Code/VSCode/sst-python-api/packages/functions/node_modules/music-metadata/lib/ogg/OggParser.js:74:35)
    at async parse (file:///Users/xxx/Desktop/Code/VSCode/sst-python-api/packages/functions/node_modules/music-metadata/lib/ParserFactory.js:35:5)
    at async parseFile (file:///Users/xxx/Desktop/Code/VSCode/sst-python-api/packages/functions/node_modules/music-metadata/lib/index.js:39:16)
    at async file:///Users/xxx/Desktop/Code/VSCode/sst-python-api/packages/functions/src/new.ts:42:1
```

### Expected Behavior

Run without issues.

Problem is that I cannot upload to file due to privacy reasons - is there any hint I should be looking for?

### Attached audio sample?

- [X] I have provided sufficient information to reproduce the issue

**Comment by Borewit** [comment]
Can you provide an audio sample please?
