### ISSUE TITLE
Unexpected "out of range" error in APEv2Parser.parseTags()

### ISSUE THREAD

**Issue by msikma** [Borewit/music-metadata#2100]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### music-metadata version

8.3.0

### JavaScript module eco system

ECMAScript modules (ESM), music-medata ≥ version 8

### Current Behavior

When parsing the given file "13-newip-Crimsonland-Across The Crimson Lands-DoD.mp3" from the [DoD project (April 2016, track 13)](https://www.dwellingofduels.net/duels/16-04-fresh/) [(direct file link)](https://dodarchive.dwellingofduels.net/16-04-Fresh/13-newip-Crimsonland-Across%20The%20Crimson%20Lands-DoD.mp3), the following error occurs:

```
ERR_OUT_OF_RANGE RangeError [ERR_OUT_OF_RANGE]: The value of "length" is out of range. It must be >= 0. Received -1431655663
    at Object.read (node:fs:673:3)
    at file:///Users/msikma/Files/Work/Code/musidx/node_modules/strtok3/lib/FsPromise.js:39:12
    at new Promise (<anonymous>)
    at Module.read (file:///Users/msikma/Files/Work/Code/musidx/node_modules/strtok3/lib/FsPromise.js:38:12)
    at FileTokenizer.peekBuffer (file:///Users/msikma/Files/Work/Code/musidx/node_modules/strtok3/lib/FileTokenizer.js:33:30)
    at APEv2Parser.parseTags (file:///Users/msikma/Files/Work/Code/musidx/node_modules/music-metadata/lib/apev2/APEv2Parser.js:101:34)
    at async ID3v1Parser.parse (file:///Users/msikma/Files/Work/Code/musidx/node_modules/music-metadata/lib/id3v1/ID3v1Parser.js:96:13)
    at async MpegParser.parseID3v2 (file:///Users/msikma/Files/Work/Code/musidx/node_modules/music-metadata/lib/id3v2/AbstractID3Parser.js:44:13)
    at async MpegParser.parse (file:///Users/msikma/Files/Work/Code/musidx/node_modules/music-metadata/lib/id3v2/AbstractID3Parser.js:21:13)
    at async parse (file:///Users/msikma/Files/Work/Code/musidx/node_modules/music-metadata/lib/ParserFactory.js:35:5)
```

### Expected Behavior

The file is parsed, and metadata such as the title and artist are returned.

As far as I can tell the file should work, and it opens fine in mp3tag.

This file is a free release from a community music project, so it can be [freely downloaded for testing](https://dodarchive.dwellingofduels.net/16-04-Fresh/13-newip-Crimsonland-Across%20The%20Crimson%20Lands-DoD.mp3).

### Attached audio sample?

- [X] I have provided sufficient information to reproduce the issue

**Comment by Borewit** [comment]
Although I did find some problems in the APE-Header-Parser, I think the header in this file is corrupt.

![image](https://github.com/user-attachments/assets/395c31a9-6fcd-48f1-a17b-091d6c7e3606)

The `APETAGEX` indicates the start of the 32 byte long APE header.
This was detected as the footer, and not the header calculating a wrong offset.

The header is appearing before the meta tags, the header after the meta tags, and then there are cases where only 1 of those headers are used. 

Anyway, solved that, but after the 32 byte footer the 10 byte APE Tag Item is expected to start. This is where you see `TAGA`, yet that `TAGA` should be the tag size, which is clearly is not. This is the where I believe the TAG header is corrupt.

**Comment by Borewit** [comment]
Feel free to re-open, if there are any updates.
