### ISSUE TITLE
Parse m4a audio file failed

### ISSUE THREAD

**Issue by Borewit** [Borewit/music-metadata#318]
Original issue: tvararu/music.vararu.org#68

PR: #319

**Comment by Borewit** [comment]
Seems to get out of sync just after the audio data (`mdat` atom):
```
...
  music-metadata:parser:MP4:Atom parse atom name=mp4/moov/udta/meta/free, extended=false, offset=113397, len=4096 +1ms
  music-metadata:parser:MP4 Ignore atom data: path=mp4/moov/udta/meta/free, payload-len=4088 +31ms
  music-metadata:parser:MP4:Atom parse atom name=mp4/mdat, extended=false, offset=117493, len=20400078 +1ms
  music-metadata:collector format: bitrate = 263159.4135535233 +3ms
  music-metadata:parser:MP4 Ignore atom data: path=mp4/mdat, payload-len=20400070 +6m

Error: FourCC contains invalid characters: 48 b5 9b 70
    at Object.get (lib\common\FourCC.ts:16:13)
    at Object.get (lib\mp4\AtomToken.ts:145:25)
    at FileTokenizer.readToken (C:\Users\Maarten\code\github\strtok3\lib\AbstractTokenizer.ts:39:18)
    at Atom.readAtom (lib\mp4\Atom.ts:35:20)
    at Atom.readAtoms (lib\mp4\Atom.ts:24:24)
    at MP4Parser.parse (lib\mp4\MP4Parser.ts:115:5)
    at Function._parse (lib\ParserFactory.ts:189:5)
    at Object.parseFile (lib\index.ts:62:12)
    at Context.<anonymous> (test\_test-issues.ts:1712:22)
```

**Comment by Borewit** [comment]
It actually looks like the m4a file is corrupt. To me it looks like either the mdat atom length is too short, or the file is appended with noise or currupted data after the mdat atom.

I did a integrity check with FoorBar2000, which does find something: 
![image](https://user-images.githubusercontent.com/23255260/68619566-027ff080-04cc-11ea-8d72-ba5d776c7a86.png)
But it is hard to say if it complains about the same thing.

Why does jsmediatags has no issue with those m4a file?

It reads much less information from the m4a file.

**Comment by Borewit** [comment]
Invalid appending data ignored in [v4.9.0](https://www.npmjs.com/package/music-metadata/v/4.9.0).
