### ISSUE TITLE
this.s.once is not a function

### ISSUE THREAD

**Issue by thisisnish** [Borewit/music-metadata#43]
While trying to read an audio stream, the package throw below error. 

`     Uncaught TypeError: this.s.once is not a function
      at new StreamReader (node_modules/then-read-stream/lib/index.js:28:16)
      at new ReadStreamTokenizer (node_modules/strtok3/lib/ReadStreamTokenizer.js:20:30)
      at Object.fromStream (node_modules/strtok3/lib/index.js:37:28)
      at Function.ParserFactory.parseStream (node_modules/music-metadata/lib/ParserFactory.js:54:24)
      at MusicMetadataParser.parseStream (node_modules/music-metadata/lib/index.js:103:46)
      at Object.parseStream (node_modules/music-metadata/lib/index.js:289:46)
      at audioType (app/controllers/uploads.js:63:15)
      at IncomingMessage.<anonymous> (app/controllers/uploads.js:104:11)
      at IncomingMessage.Readable.read (_stream_readable.js:381:10)
      at flow (_stream_readable.js:761:34)
      at resume_ (_stream_readable.js:743:3)
      at _combinedTickCallback (internal/process/next_tick.js:74:11)
      at process._tickDomainCallback (internal/process/next_tick.js:122:9)`

**Comment by thisisnish** [comment]
https://github.com/Borewit/then-read-stream/issues/3

**Comment by Borewit** [comment]
It looks like that the argument `stream` you provide to `MusicMetadataParser.parseStream(stream: Stream.Readable, mimeType: string, opts?: IOptions)` is actually not [stream (instance of Stream.Readable)](https://nodejs.org/api/stream.html#stream_class_stream_readable).

I released a [new version of then-read-stream](https://github.com/Borewit/then-read-stream/releases/tag/v1.0.4) which checks the argument and throws an error if a stream is not provided.

Let me know if I can help you with something.
