### ISSUE TITLE
Error: Cannot find module 'strtok3/lib/type'

### ISSUE THREAD

**Issue by meowsus** [Borewit/music-metadata#475]
I'm curious if anyone else has experienced this issue recently.

**Bug description**
I wrote [a script](https://github.com/meowsus/fauxfetus.net/blob/master/scripts/scrape_track_metadata.js) to scrape ID3 data from 6GB of audio files, transform it, and save it to JSON. [The JSON](https://github.com/meowsus/fauxfetus.net/blob/master/public/catalog.json) is then used to hydrate a React app. This script was working 2 months ago when I last ran it. Trying to run it again I get this error:

```
$ node scripts/scrape_track_metadata.js
internal/modules/cjs/loader.js:985
  throw err;
  ^

Error: Cannot find module 'strtok3/lib/type'
Require stack:
- /home/meowsus/Sandbox/github/meowsus/fauxfetus.net/node_modules/music-metadata/lib/aiff/AiffParser.js
- /home/meowsus/Sandbox/github/meowsus/fauxfetus.net/node_modules/music-metadata/lib/ParserFactory.js
- /home/meowsus/Sandbox/github/meowsus/fauxfetus.net/node_modules/music-metadata/lib/core.js
- /home/meowsus/Sandbox/github/meowsus/fauxfetus.net/node_modules/music-metadata/lib/index.js
- /home/meowsus/Sandbox/github/meowsus/fauxfetus.net/scripts/scrape_track_metadata.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:982:15)
    at Function.Module._load (internal/modules/cjs/loader.js:864:27)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/home/meowsus/Sandbox/github/meowsus/fauxfetus.net/node_modules/music-metadata/lib/aiff/AiffParser.js:5:16)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/meowsus/Sandbox/github/meowsus/fauxfetus.net/node_modules/music-metadata/lib/aiff/AiffParser.js',
    '/home/meowsus/Sandbox/github/meowsus/fauxfetus.net/node_modules/music-metadata/lib/ParserFactory.js',
    '/home/meowsus/Sandbox/github/meowsus/fauxfetus.net/node_modules/music-metadata/lib/core.js',
    '/home/meowsus/Sandbox/github/meowsus/fauxfetus.net/node_modules/music-metadata/lib/index.js',
    '/home/meowsus/Sandbox/github/meowsus/fauxfetus.net/scripts/scrape_track_metadata.js'
  ]
}
error Command failed with exit code 1.
```

**Expected behavior**
I'd expect music-metadata to load its dependencies properly.

**Comment by meowsus** [comment]
This seems to be related to Borewit/strtok3#187

**Comment by meowsus** [comment]
... I am a doof. This is fixed in the newest version of the package.
