### ISSUE TITLE
buf.readInt16BE is not a function

### ISSUE THREAD

**Issue by qboisson** [Borewit/music-metadata#856]
When trying to use parseFile on mp3 files, thanks to a Node script, I have the following error on some files:

```
TypeError: buf.readInt16BE is not a function
    at Object.get (/Users/quentin/Desktop/audio-resource-manager/node_modules/token-types/lib/index.js:108:20)
    at FileTokenizer.readNumber (/Users/quentin/Desktop/audio-resource-manager/node_modules/strtok3/lib/AbstractTokenizer.js:52:22)
    at MpegParser.parseCrc (/Users/quentin/Desktop/audio-resource-manager/node_modules/music-metadata/lib/mpeg/MpegParser.js:432:20)
    at MpegParser.parseAudioFrameHeader (/Users/quentin/Desktop/audio-resource-manager/node_modules/music-metadata/lib/mpeg/MpegParser.js:396:13)
    at MpegParser._parse (/Users/quentin/Desktop/audio-resource-manager/node_modules/music-metadata/lib/mpeg/MpegParser.js:233:24)
    at MpegParser.parseID3v2 (/Users/quentin/Desktop/audio-resource-manager/node_modules/music-metadata/lib/id3v2/AbstractID3Parser.js:41:9)
    at MpegParser.parse (/Users/quentin/Desktop/audio-resource-manager/node_modules/music-metadata/lib/id3v2/AbstractID3Parser.js:24:13)
    at Function._parse (/Users/quentin/Desktop/audio-resource-manager/node_modules/music-metadata/lib/ParserFactory.js:161:9)
    at parseFile (/Users/quentin/Desktop/audio-resource-manager/node_modules/music-metadata/lib/index.js:46:16)
```

Node v16.5.0
MacOS BigSur

Bug mp3 file example: [Example file.zip](https://github.com/Borewit/music-metadata/files/6841563/Example.file.zip)

Not sure if it can help but I did not have the issue with music-metadata@7.8.5 but with music-metadata@7.8.8.
And now, returning on music-metadata@7.8.5 is not working anymore.

**Comment by Borewit** [comment]
It is probably one of the (my) dependant modules. Maybe token-types. 
Can you please check that version? Are running this code with node.js or the browser?

**Comment by Borewit** [comment]
Similar issue: sindresorhus/file-type#469

**Comment by Borewit** [comment]
Is your issue solved @qboisson by upgrading to [music-metadata v7.9.0](https://github.com/Borewit/music-metadata/releases/tag/v7.9.0)?

**Comment by qboisson** [comment]
Thanks for the reply.
The code is running with node.js.
strtok3 version: 6.2.2 and token-types version: 2.1.1

**Comment by RomanBurunkov** [comment]
Hi @Borewit ,

I've just tried 7.9.0 but still getting 'buf.readInt16BE is not a function'

**Comment by Borewit** [comment]
Ah, okay good, just did [another release](https://github.com/Borewit/music-metadata/releases/tag/v7.9.1) to freeze the version of the problematic dependencies.
