### ISSUE TITLE
Error when parsing wav file

### ISSUE THREAD

**Issue by IrosTheBeggar** [Borewit/music-metadata#90]
Hey,

I've got a wav file that throws this error.

```
stdout: Error: expected file identifier 'ID3' not found
    at /Users/p/Documents/mStream/node_modules/music-metadata/lib/id3v2/ID3v2Parser.js:117:23
    at tryCatcher (/Users/p/Documents/mStream/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/p/Documents/mStream/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/p/Documents/mStream/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/p/Documents/mStream/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/p/Documents/mStream/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/Users/p/Documents/mStream/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/Users/p/Documents/mStream/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/Users/p/Documents/mStream/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
```

I can send you the file if necessary.

**Comment by Borewit** [comment]
Hey Paul.
It is hard to cure the patient if she is not present.
Can you please provide the file?

**Comment by IrosTheBeggar** [comment]
First file: https://www.dropbox.com/s/s07cn66xf2ae4yx/Tamiko%20Jones%20-%20Can%27t%20Live%20Without%20Your%20Love%20%28Full%20Length%20Version%29.wav?dl=0

**Comment by Borewit** [comment]
The first file has a strange RIFF/EXIF tag 'GNR\u0001':
```
------[exif]------
{ IART: [ 'Shooting party' ],
  'GNR\u0001': [ '' ],
  INAM: [ 'Show me the way to your heart' ],
  ICRD: [ '1990' ] }
```
The '\u0001' is considered to be illegal (for good or bad reasons), causing the exception

The second file has an ID3 chunk defined, which is normally used for ID3v2 header. The header identifier is set to `TAG` instead usual `ID3`. I suspect one managed to squeeze a ID3v1 header in. ID3v1 header are typically the last 128 bytes of an audio file, I have never seen them in the middle of a file.

**Comment by IrosTheBeggar** [comment]
Thanks for looking into this!

**Comment by Borewit** [comment]
No problem Paul, I will close the issue.

**Comment by Borewit** [comment]
Maybe useful to return an indication what is wrong: #60
